set(SOURCES
	include/REL/ASM.h
	include/REL/FHook.h
	include/REL/FHookStore.h
	include/REL/IAT.h
	include/REL/ID.h
	include/REL/IDDB.h
	include/REL/IHook.h
	include/REL/Offset.h
	include/REL/Offset2ID.h
	include/REL/Pattern.h
	include/REL/REL.h
	include/REL/Relocation.h
	include/REL/THook.h
	include/REL/Trampoline.h
	include/REL/Utility.h
	include/REL/Version.h
	include/REX/BASE.h
	include/REX/CAST.h
	include/REX/CONVERT.h
	include/REX/FIniSettingStore.h
	include/REX/FJsonSettingStore.h
	include/REX/FMemoryMap.h
	include/REX/FModule.h
	include/REX/FModuleSection.h
	include/REX/FSettingStore.h
	include/REX/FTimer.h
	include/REX/FTomlSettingStore.h
	include/REX/FUUID.h
	include/REX/HASH.h
	include/REX/ISetting.h
	include/REX/ISettingStore.h
	include/REX/LOG.h
	include/REX/PS4.h
	include/REX/PS4/SCEPAD.h
	include/REX/REX.h
	include/REX/REX/AtomicRef.h
	include/REX/REX/CAST.h
	include/REX/REX/CONVERT.h
	include/REX/REX/Enum.h
	include/REX/REX/EnumSet.h
	include/REX/REX/HASH.h
	include/REX/REX/INI.h
	include/REX/REX/JSON.h
	include/REX/REX/LOG.h
	include/REX/REX/MemoryMap.h
	include/REX/REX/ScopeExit.h
	include/REX/REX/Singleton.h
	include/REX/REX/StaticString.h
	include/REX/REX/TOML.h
	include/REX/STRING.h
	include/REX/TAtomicRef.h
	include/REX/TEnum.h
	include/REX/TEnumSet.h
	include/REX/TIniSetting.h
	include/REX/TIniSettingA.h
	include/REX/TJsonSetting.h
	include/REX/TScopeExit.h
	include/REX/TSetting.h
	include/REX/TSingleton.h
	include/REX/TStaticString.h
	include/REX/TTomlSetting.h
	include/REX/W32.h
	include/REX/W32/ADVAPI32.h
	include/REX/W32/BASE.h
	include/REX/W32/BCRYPT.h
	include/REX/W32/COM.h
	include/REX/W32/COMPTR.h
	include/REX/W32/D3D.h
	include/REX/W32/D3D11.h
	include/REX/W32/D3D11_1.h
	include/REX/W32/D3D11_2.h
	include/REX/W32/D3D11_3.h
	include/REX/W32/D3D11_4.h
	include/REX/W32/D3D12.h
	include/REX/W32/D3DCOMPILER.h
	include/REX/W32/DBGHELP.h
	include/REX/W32/DINPUT.h
	include/REX/W32/DXGI.h
	include/REX/W32/DXGI_2.h
	include/REX/W32/DXGI_3.h
	include/REX/W32/DXGI_4.h
	include/REX/W32/DXGI_5.h
	include/REX/W32/DXGI_6.h
	include/REX/W32/KERNEL32.h
	include/REX/W32/MACRO_GUARD_BEGIN.h
	include/REX/W32/MACRO_GUARD_END.h
	include/REX/W32/NT.h
	include/REX/W32/OLE32.h
	include/REX/W32/RTTI.h
	include/REX/W32/SHELL32.h
	include/REX/W32/USER32.h
	include/REX/W32/VERSION.h
	include/REX/W32/WS2_32.h
	include/REX/W32/X3DAUDIO.h
	include/REX/W32/XAPO.h
	include/REX/W32/XAUDIO2.h
	include/REX/W32/XAUDIO2FX.h
	include/REX/W32/XINPUT.h
	src/REL/FHook.cpp
	src/REL/FHookStore.cpp
	src/REL/IAT.cpp
	src/REL/IDDB.cpp
	src/REL/Offset2ID.cpp
	src/REL/Trampoline.cpp
	src/REL/Utility.cpp
	src/REL/Version.cpp
	src/REX/FIniSettingStore.cpp
	src/REX/FJsonSettingStore.cpp
	src/REX/FModule.cpp
	src/REX/FTomlSettingStore.cpp
	src/REX/LOG.cpp
	src/REX/PCH.h
	src/REX/REX.cpp
	src/REX/TIniSetting.cpp
	src/REX/TIniSettingA.cpp
	src/REX/TJsonSetting.cpp
	src/REX/TTomlSetting.cpp
	src/REX/W32.cpp
)
